[window]
decorations = "buttonless"
opacity = 0.95
blur = true
startup_mode = "Maximized"
decorations_theme_variant = "Dark"

[scrolling]
history = 100000

[font]
normal = { family = "FiraCode Nerd Font" }
size = 15

[colors.primary]
background = "#000000"

[cursor]
style = { shape = "Block", blinking = "On"}

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"
